Developer
TashfeenRao/The-Next-Web pull request #1
Opened 2019-11-22 15:12 UTC by TashfeenRao

2019-11-22 21:32 UTC, suretrust requested changes
Hi team!

### Amazing job thus far, :raised_hands:  just a few suggestions to wrap it up. Please see my comments on your code.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-22 21:32 UTC, suretrust commented on css/media.css
> +}
There are some problems with your media queries. Some overflow (horizontal navbar) appears between 750px and 820px as well as between 1024px and 1145px screens.

![vaertical](https://user-images.githubusercontent.com/31304943/69455151-0e8b6e00-0d68-11ea-9241-23c28adc4a64.png)

2019-11-22 21:32 UTC, suretrust commented on index.html
> +            <li><a href="#">Contact</a></li>
On medium screen size, the navigation bar is different from the one in your design.

**Yours**
![nav2](https://user-images.githubusercontent.com/31304943/69455551-ec462000-0d68-11ea-8728-8b11f5daa164.png)



**Original**
![nav](https://user-images.githubusercontent.com/31304943/69455507-d46e9c00-0d68-11ea-9b99-47025416eeb4.png)

2019-11-22 21:32 UTC, suretrust commented on index.html
> +                alt=""
On large screen, the latest news should have 4 rows.

**Original**
![latest2](https://user-images.githubusercontent.com/31304943/69456000-eef54500-0d69-11ea-83c2-830fdd357fe0.png)



**Yours**
![latest](https://user-images.githubusercontent.com/31304943/69455930-bfded380-0d69-11ea-8e4f-12ace55927ca.png)

2019-11-22 21:32 UTC, suretrust commented on index.html
> +            </li>
This section on medium screen looks different from your design.

**Original**
![head2](https://user-images.githubusercontent.com/31304943/69456283-86f32e80-0d6a-11ea-8a22-856d4ee68a0b.png)


**Yours**
![head](https://user-images.githubusercontent.com/31304943/69456242-7347c800-0d6a-11ea-9972-e96925f8f1d8.png)

2019-11-22 21:32 UTC, suretrust commented on index.html
> +            </li>
On small screen, the navbar has the hamburger symbol.

**Yours**
![nav](https://user-images.githubusercontent.com/31304943/69461748-9af15d00-0d77-11ea-864d-bfe01ba262c4.png)

**Original**
![nav2](https://user-images.githubusercontent.com/31304943/69461747-9af15d00-0d77-11ea-9a7d-3da4a9180c08.png)

2019-11-24 18:54 UTC, shshamim63 commented
## Status :red_circle: [!!Required Changes!!] :red_circle: 
___
Hi @TashfeenRao & @mekinus :wave: ,
Great job :clap: . I can see you have covered some issues that has been raised by the previous TSE. But I think there are some issues that you need to fix too. Well I am sure you guys will complete it. 
#### Please follow the instructions below :point_down: to declare this project as complete.
___
## :spades: [Mandatory Changes] :spades: 
___
### :large_blue_diamond:  Navbar :large_blue_diamond: 
___
####  Medium screen
___
1. Well on the medium screen size, on the navbar the TNW logo should appear. But I can not see it on your project.
##### Your Project--->
![tnwlogomedium](https://user-images.githubusercontent.com/38625956/69499343-35d66c80-0f1b-11ea-9302-b2cb75b218f6.png)
##### Actual Webpage--->
![actual logo](https://user-images.githubusercontent.com/38625956/69499348-59011c00-0f1b-11ea-9f4d-507e5974558b.png)
2. This is project is about responsive web design. So your elements should interact with respect to the window size. And a feature of this is, it should contain all the element without overflowing. But I can see it. On screen- size `754px-850px` the page is overflowing.
![overflow](https://user-images.githubusercontent.com/38625956/69499447-6b2f8a00-0f1c-11ea-8b07-e3610f9d208d.png)
![overflow2](https://user-images.githubusercontent.com/38625956/69499481-bb0e5100-0f1c-11ea-8bcc-5838970e30f7.png)
It is because of the fixed width. For an example width: 250px;
 ___
####  Mobile screen
___
1. Items are overflowing. Think about the width. What do you think about using the width in percentage(%)? For an example width: 45%;
![footer](https://user-images.githubusercontent.com/38625956/69499551-6919fb00-0f1d-11ea-851e-d3e9a05164b8.png)
![footerover2](https://user-images.githubusercontent.com/38625956/69499568-98306c80-0f1d-11ea-8f3b-9c077ef2a12f.png)
___
#### Please fix the above mentioned issue and send another code review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

2019-11-25 00:06 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Well done implementing the changes, but we need to fix the issues below before moving on ⬇️** 

- On medium screen sizes and when the logo appears on the navbar the big logo should disappear, on your page, they are both showing at the same time, please fix that.

<img width="1513" alt="Screen Shot 2019-11-24 at 7 05 20 PM" src="https://user-images.githubusercontent.com/33462180/69504015-61daf900-0eed-11ea-907f-7ce3f4cd21e5.png">

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-25 16:54 UTC, imhta approved these changes
# Project Approved 👍 

### Hello @TashfeenRao @mekinus , 👋 You have done great job with this project. 👏 

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">

----
#### Don't forgot to sumbit project completion form
 **Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

2019-11-25 21:10 UTC, merged